"""
Prepare:
    test.txt
        this file was generated by the following code:
            from PySide6.QtWidgets import *
            from lk_utils.read_and_write import dumps
            
            widget_names = []
            locals_ = str(locals()).split(',')
            
            for i in locals_:
                print(i)  # e.g. " 'QMainWindow': <QMainWindow ...>"
                if i.startswith(' \''):
                    if i[2] == 'Q':
                        widget_names.append(i[3:].split('\'')[0])
                        #   i[3:].split('\'')[0]: e.g. 'MainWindow'
            
            dumps(widget_names, 'test.txt')
"""
from textwrap import dedent
from lk_utils.read_and_write import dumps, load_list


def _fmt_string(s: str):
    return dedent(s)[1:]


# the `file_template` relates to `declare_qt/components/qt_widgets.py`, you can
# consider it as that file.
file_template = _fmt_string('''
    """
    Notes:
        This file is auto generated by
            `blueprint/generate_qtwidgets_from_template.py`.

    Usages:
        from declare_qt import Application, Label, MainWindow, VBox

        with Application() as app:
            with MainWindow() as win:
                with VBox() as vbox:
                    with Label() as label:
                        label.setText('Hello World')
                        vbox.addWidget(label)
    """
    from PySide6 import QtWidgets

    from .base_component import BaseComponent


    {HTML_COMPONENTS}
''')

template = _fmt_string('''
    class {WIDGET_NAME}(QtWidgets.Q{WIDGET_NAME}, BaseComponent):
        pass
''')

components = []

for tag in sorted(load_list('test.txt')):
    if tag == '': continue
    components.append(
        template.format(WIDGET_NAME=tag)
    )

dumps(
    file_template.format(HTML_COMPONENTS='\n\n'.join(components)).rstrip(),
    '../components/qt_widgets.py'
)
