"""
Notes:
    This file is auto generated by
        `blueprint/generate_qtwidgets_from_template.py`.

Usages:
    from declare_qt import Application, MainWindow, Label

    with Application() as app:
        with MainWindow() as win:
            with Label() as label:
                label.setText('Hello World')
"""
from PySide6 import QtWidgets

from .base_component import BaseComponent


class AbstractButton(QtWidgets.QAbstractButton, BaseComponent):
    pass


class AbstractGraphicsShapeItem(QtWidgets.QAbstractGraphicsShapeItem, BaseComponent):
    pass


class AbstractItemDelegate(QtWidgets.QAbstractItemDelegate, BaseComponent):
    pass


class AbstractItemView(QtWidgets.QAbstractItemView, BaseComponent):
    pass


class AbstractScrollArea(QtWidgets.QAbstractScrollArea, BaseComponent):
    pass


class AbstractSlider(QtWidgets.QAbstractSlider, BaseComponent):
    pass


class AbstractSpinBox(QtWidgets.QAbstractSpinBox, BaseComponent):
    pass


class AccessibleWidget(QtWidgets.QAccessibleWidget, BaseComponent):
    pass


class Application(QtWidgets.QApplication, BaseComponent):
    pass


class BoxLayout(QtWidgets.QBoxLayout, BaseComponent):
    pass


class ButtonGroup(QtWidgets.QButtonGroup, BaseComponent):
    pass


class CalendarWidget(QtWidgets.QCalendarWidget, BaseComponent):
    pass


class CheckBox(QtWidgets.QCheckBox, BaseComponent):
    pass


class ColorDialog(QtWidgets.QColorDialog, BaseComponent):
    pass


class Colormap(QtWidgets.QColormap, BaseComponent):
    pass


class ColumnView(QtWidgets.QColumnView, BaseComponent):
    pass


class ComboBox(QtWidgets.QComboBox, BaseComponent):
    pass


class CommandLinkButton(QtWidgets.QCommandLinkButton, BaseComponent):
    pass


class CommonStyle(QtWidgets.QCommonStyle, BaseComponent):
    pass


class Completer(QtWidgets.QCompleter, BaseComponent):
    pass


class DataWidgetMapper(QtWidgets.QDataWidgetMapper, BaseComponent):
    pass


class DateEdit(QtWidgets.QDateEdit, BaseComponent):
    pass


class DateTimeEdit(QtWidgets.QDateTimeEdit, BaseComponent):
    pass


class Dial(QtWidgets.QDial, BaseComponent):
    pass


class Dialog(QtWidgets.QDialog, BaseComponent):
    pass


class DialogButtonBox(QtWidgets.QDialogButtonBox, BaseComponent):
    pass


class DockWidget(QtWidgets.QDockWidget, BaseComponent):
    pass


class DoubleSpinBox(QtWidgets.QDoubleSpinBox, BaseComponent):
    pass


class ErrorMessage(QtWidgets.QErrorMessage, BaseComponent):
    pass


class FileDialog(QtWidgets.QFileDialog, BaseComponent):
    pass


class FileIconProvider(QtWidgets.QFileIconProvider, BaseComponent):
    pass


class FileSystemModel(QtWidgets.QFileSystemModel, BaseComponent):
    pass


class FocusFrame(QtWidgets.QFocusFrame, BaseComponent):
    pass


class FontComboBox(QtWidgets.QFontComboBox, BaseComponent):
    pass


class FontDialog(QtWidgets.QFontDialog, BaseComponent):
    pass


class FormLayout(QtWidgets.QFormLayout, BaseComponent):
    pass


class Frame(QtWidgets.QFrame, BaseComponent):
    pass


class Gesture(QtWidgets.QGesture, BaseComponent):
    pass


class GestureEvent(QtWidgets.QGestureEvent, BaseComponent):
    pass


class GestureRecognizer(QtWidgets.QGestureRecognizer, BaseComponent):
    pass


class GraphicsAnchor(QtWidgets.QGraphicsAnchor, BaseComponent):
    pass


class GraphicsAnchorLayout(QtWidgets.QGraphicsAnchorLayout, BaseComponent):
    pass


class GraphicsBlurEffect(QtWidgets.QGraphicsBlurEffect, BaseComponent):
    pass


class GraphicsColorizeEffect(QtWidgets.QGraphicsColorizeEffect, BaseComponent):
    pass


class GraphicsDropShadowEffect(QtWidgets.QGraphicsDropShadowEffect, BaseComponent):
    pass


class GraphicsEffect(QtWidgets.QGraphicsEffect, BaseComponent):
    pass


class GraphicsEllipseItem(QtWidgets.QGraphicsEllipseItem, BaseComponent):
    pass


class GraphicsGridLayout(QtWidgets.QGraphicsGridLayout, BaseComponent):
    pass


class GraphicsItem(QtWidgets.QGraphicsItem, BaseComponent):
    pass


class GraphicsItemAnimation(QtWidgets.QGraphicsItemAnimation, BaseComponent):
    pass


class GraphicsItemGroup(QtWidgets.QGraphicsItemGroup, BaseComponent):
    pass


class GraphicsLayout(QtWidgets.QGraphicsLayout, BaseComponent):
    pass


class GraphicsLayoutItem(QtWidgets.QGraphicsLayoutItem, BaseComponent):
    pass


class GraphicsLineItem(QtWidgets.QGraphicsLineItem, BaseComponent):
    pass


class GraphicsLinearLayout(QtWidgets.QGraphicsLinearLayout, BaseComponent):
    pass


class GraphicsObject(QtWidgets.QGraphicsObject, BaseComponent):
    pass


class GraphicsOpacityEffect(QtWidgets.QGraphicsOpacityEffect, BaseComponent):
    pass


class GraphicsPathItem(QtWidgets.QGraphicsPathItem, BaseComponent):
    pass


class GraphicsPixmapItem(QtWidgets.QGraphicsPixmapItem, BaseComponent):
    pass


class GraphicsPolygonItem(QtWidgets.QGraphicsPolygonItem, BaseComponent):
    pass


class GraphicsProxyWidget(QtWidgets.QGraphicsProxyWidget, BaseComponent):
    pass


class GraphicsRectItem(QtWidgets.QGraphicsRectItem, BaseComponent):
    pass


class GraphicsRotation(QtWidgets.QGraphicsRotation, BaseComponent):
    pass


class GraphicsScale(QtWidgets.QGraphicsScale, BaseComponent):
    pass


class GraphicsScene(QtWidgets.QGraphicsScene, BaseComponent):
    pass


class GraphicsSceneContextMenuEvent(QtWidgets.QGraphicsSceneContextMenuEvent, BaseComponent):
    pass


class GraphicsSceneDragDropEvent(QtWidgets.QGraphicsSceneDragDropEvent, BaseComponent):
    pass


class GraphicsSceneEvent(QtWidgets.QGraphicsSceneEvent, BaseComponent):
    pass


class GraphicsSceneHelpEvent(QtWidgets.QGraphicsSceneHelpEvent, BaseComponent):
    pass


class GraphicsSceneHoverEvent(QtWidgets.QGraphicsSceneHoverEvent, BaseComponent):
    pass


class GraphicsSceneMouseEvent(QtWidgets.QGraphicsSceneMouseEvent, BaseComponent):
    pass


class GraphicsSceneMoveEvent(QtWidgets.QGraphicsSceneMoveEvent, BaseComponent):
    pass


class GraphicsSceneResizeEvent(QtWidgets.QGraphicsSceneResizeEvent, BaseComponent):
    pass


class GraphicsSceneWheelEvent(QtWidgets.QGraphicsSceneWheelEvent, BaseComponent):
    pass


class GraphicsSimpleTextItem(QtWidgets.QGraphicsSimpleTextItem, BaseComponent):
    pass


class GraphicsTextItem(QtWidgets.QGraphicsTextItem, BaseComponent):
    pass


class GraphicsTransform(QtWidgets.QGraphicsTransform, BaseComponent):
    pass


class GraphicsView(QtWidgets.QGraphicsView, BaseComponent):
    pass


class GraphicsWidget(QtWidgets.QGraphicsWidget, BaseComponent):
    pass


class GridLayout(QtWidgets.QGridLayout, BaseComponent):
    pass


class GroupBox(QtWidgets.QGroupBox, BaseComponent):
    pass


class HBoxLayout(QtWidgets.QHBoxLayout, BaseComponent):
    pass


class HeaderView(QtWidgets.QHeaderView, BaseComponent):
    pass


class InputDialog(QtWidgets.QInputDialog, BaseComponent):
    pass


class ItemDelegate(QtWidgets.QItemDelegate, BaseComponent):
    pass


class ItemEditorCreatorBase(QtWidgets.QItemEditorCreatorBase, BaseComponent):
    pass


class ItemEditorFactory(QtWidgets.QItemEditorFactory, BaseComponent):
    pass


class KeySequenceEdit(QtWidgets.QKeySequenceEdit, BaseComponent):
    pass


class LCDNumber(QtWidgets.QLCDNumber, BaseComponent):
    pass


class Label(QtWidgets.QLabel, BaseComponent):
    pass


class Layout(QtWidgets.QLayout, BaseComponent):
    pass


class LayoutItem(QtWidgets.QLayoutItem, BaseComponent):
    pass


class LineEdit(QtWidgets.QLineEdit, BaseComponent):
    pass


class ListView(QtWidgets.QListView, BaseComponent):
    pass


class ListWidget(QtWidgets.QListWidget, BaseComponent):
    pass


class ListWidgetItem(QtWidgets.QListWidgetItem, BaseComponent):
    pass


class MainWindow(QtWidgets.QMainWindow, BaseComponent):
    pass


class MdiArea(QtWidgets.QMdiArea, BaseComponent):
    pass


class MdiSubWindow(QtWidgets.QMdiSubWindow, BaseComponent):
    pass


class Menu(QtWidgets.QMenu, BaseComponent):
    pass


class MenuBar(QtWidgets.QMenuBar, BaseComponent):
    pass


class MessageBox(QtWidgets.QMessageBox, BaseComponent):
    pass


class PanGesture(QtWidgets.QPanGesture, BaseComponent):
    pass


class PinchGesture(QtWidgets.QPinchGesture, BaseComponent):
    pass


class PlainTextDocumentLayout(QtWidgets.QPlainTextDocumentLayout, BaseComponent):
    pass


class PlainTextEdit(QtWidgets.QPlainTextEdit, BaseComponent):
    pass


class ProgressBar(QtWidgets.QProgressBar, BaseComponent):
    pass


class ProgressDialog(QtWidgets.QProgressDialog, BaseComponent):
    pass


class ProxyStyle(QtWidgets.QProxyStyle, BaseComponent):
    pass


class PushButton(QtWidgets.QPushButton, BaseComponent):
    pass


class RadioButton(QtWidgets.QRadioButton, BaseComponent):
    pass


class RubberBand(QtWidgets.QRubberBand, BaseComponent):
    pass


class ScrollArea(QtWidgets.QScrollArea, BaseComponent):
    pass


class ScrollBar(QtWidgets.QScrollBar, BaseComponent):
    pass


class Scroller(QtWidgets.QScroller, BaseComponent):
    pass


class ScrollerProperties(QtWidgets.QScrollerProperties, BaseComponent):
    pass


class SizeGrip(QtWidgets.QSizeGrip, BaseComponent):
    pass


class SizePolicy(QtWidgets.QSizePolicy, BaseComponent):
    pass


class Slider(QtWidgets.QSlider, BaseComponent):
    pass


class SpacerItem(QtWidgets.QSpacerItem, BaseComponent):
    pass


class SpinBox(QtWidgets.QSpinBox, BaseComponent):
    pass


class SplashScreen(QtWidgets.QSplashScreen, BaseComponent):
    pass


class Splitter(QtWidgets.QSplitter, BaseComponent):
    pass


class SplitterHandle(QtWidgets.QSplitterHandle, BaseComponent):
    pass


class StackedLayout(QtWidgets.QStackedLayout, BaseComponent):
    pass


class StackedWidget(QtWidgets.QStackedWidget, BaseComponent):
    pass


class StatusBar(QtWidgets.QStatusBar, BaseComponent):
    pass


class Style(QtWidgets.QStyle, BaseComponent):
    pass


class StyleFactory(QtWidgets.QStyleFactory, BaseComponent):
    pass


class StyleHintReturn(QtWidgets.QStyleHintReturn, BaseComponent):
    pass


class StyleHintReturnMask(QtWidgets.QStyleHintReturnMask, BaseComponent):
    pass


class StyleHintReturnVariant(QtWidgets.QStyleHintReturnVariant, BaseComponent):
    pass


class StyleOption(QtWidgets.QStyleOption, BaseComponent):
    pass


class StyleOptionButton(QtWidgets.QStyleOptionButton, BaseComponent):
    pass


class StyleOptionComboBox(QtWidgets.QStyleOptionComboBox, BaseComponent):
    pass


class StyleOptionComplex(QtWidgets.QStyleOptionComplex, BaseComponent):
    pass


class StyleOptionDockWidget(QtWidgets.QStyleOptionDockWidget, BaseComponent):
    pass


class StyleOptionFocusRect(QtWidgets.QStyleOptionFocusRect, BaseComponent):
    pass


class StyleOptionFrame(QtWidgets.QStyleOptionFrame, BaseComponent):
    pass


class StyleOptionGraphicsItem(QtWidgets.QStyleOptionGraphicsItem, BaseComponent):
    pass


class StyleOptionGroupBox(QtWidgets.QStyleOptionGroupBox, BaseComponent):
    pass


class StyleOptionHeader(QtWidgets.QStyleOptionHeader, BaseComponent):
    pass


class StyleOptionMenuItem(QtWidgets.QStyleOptionMenuItem, BaseComponent):
    pass


class StyleOptionProgressBar(QtWidgets.QStyleOptionProgressBar, BaseComponent):
    pass


class StyleOptionRubberBand(QtWidgets.QStyleOptionRubberBand, BaseComponent):
    pass


class StyleOptionSizeGrip(QtWidgets.QStyleOptionSizeGrip, BaseComponent):
    pass


class StyleOptionSlider(QtWidgets.QStyleOptionSlider, BaseComponent):
    pass


class StyleOptionSpinBox(QtWidgets.QStyleOptionSpinBox, BaseComponent):
    pass


class StyleOptionTab(QtWidgets.QStyleOptionTab, BaseComponent):
    pass


class StyleOptionTabBarBase(QtWidgets.QStyleOptionTabBarBase, BaseComponent):
    pass


class StyleOptionTabWidgetFrame(QtWidgets.QStyleOptionTabWidgetFrame, BaseComponent):
    pass


class StyleOptionTitleBar(QtWidgets.QStyleOptionTitleBar, BaseComponent):
    pass


class StyleOptionToolBar(QtWidgets.QStyleOptionToolBar, BaseComponent):
    pass


class StyleOptionToolBox(QtWidgets.QStyleOptionToolBox, BaseComponent):
    pass


class StyleOptionToolButton(QtWidgets.QStyleOptionToolButton, BaseComponent):
    pass


class StyleOptionViewItem(QtWidgets.QStyleOptionViewItem, BaseComponent):
    pass


class StylePainter(QtWidgets.QStylePainter, BaseComponent):
    pass


class StyledItemDelegate(QtWidgets.QStyledItemDelegate, BaseComponent):
    pass


class SwipeGesture(QtWidgets.QSwipeGesture, BaseComponent):
    pass


class SystemTrayIcon(QtWidgets.QSystemTrayIcon, BaseComponent):
    pass


class TabBar(QtWidgets.QTabBar, BaseComponent):
    pass


class TabWidget(QtWidgets.QTabWidget, BaseComponent):
    pass


class TableView(QtWidgets.QTableView, BaseComponent):
    pass


class TableWidget(QtWidgets.QTableWidget, BaseComponent):
    pass


class TableWidgetItem(QtWidgets.QTableWidgetItem, BaseComponent):
    pass


class TableWidgetSelectionRange(QtWidgets.QTableWidgetSelectionRange, BaseComponent):
    pass


class TapAndHoldGesture(QtWidgets.QTapAndHoldGesture, BaseComponent):
    pass


class TapGesture(QtWidgets.QTapGesture, BaseComponent):
    pass


class TextBrowser(QtWidgets.QTextBrowser, BaseComponent):
    pass


class TextEdit(QtWidgets.QTextEdit, BaseComponent):
    pass


class TileRules(QtWidgets.QTileRules, BaseComponent):
    pass


class TimeEdit(QtWidgets.QTimeEdit, BaseComponent):
    pass


class ToolBar(QtWidgets.QToolBar, BaseComponent):
    pass


class ToolBox(QtWidgets.QToolBox, BaseComponent):
    pass


class ToolButton(QtWidgets.QToolButton, BaseComponent):
    pass


class ToolTip(QtWidgets.QToolTip, BaseComponent):
    pass


class TreeView(QtWidgets.QTreeView, BaseComponent):
    pass


class TreeWidget(QtWidgets.QTreeWidget, BaseComponent):
    pass


class TreeWidgetItem(QtWidgets.QTreeWidgetItem, BaseComponent):
    pass


class TreeWidgetItemIterator(QtWidgets.QTreeWidgetItemIterator, BaseComponent):
    pass


class UndoView(QtWidgets.QUndoView, BaseComponent):
    pass


class VBoxLayout(QtWidgets.QVBoxLayout, BaseComponent):
    pass


class WhatsThis(QtWidgets.QWhatsThis, BaseComponent):
    pass


class Widget(QtWidgets.QWidget, BaseComponent):
    pass


class WidgetAction(QtWidgets.QWidgetAction, BaseComponent):
    pass


class WidgetItem(QtWidgets.QWidgetItem, BaseComponent):
    pass


class Wizard(QtWidgets.QWizard, BaseComponent):
    pass


class WizardPage(QtWidgets.QWizardPage, BaseComponent):
    pass
